### ISSUE TITLE
No buttons in the dialog box

### ISSUE THREAD

**Issue by r-monti14** [gecos-lab/PZero#100]
When importing a GOCAD object into the class_refactoring_pyside6 branch, when the dialogue box ‘Feature from name’ is displayed, there are no buttons: the ‘close’ button does not work and the dialogue box blocks the main window, so PZero has to be restarted.
![Screenshot 2024-10-09 120009](https://github.com/user-attachments/assets/a521dbb6-c3fa-4b73-9d6f-c45b9ac1d3a1)

**Comment by waqashussain117** [comment]
Fix QMessageBox button handling in options_dialog

Previously, buttons were added using QPushButton with role texts that could be None, resulting in buttons labeled "None". This caused inconsistencies between PyQt5 and PySide6, where PySide6 would display unintended button texts and the return values did not correctly reflect the clicked button.

- Set default texts for Yes and No buttons to ensure they are never None.
- Use `addButton` with text and role directly instead of creating `QPushButton` instances.
- Adjust return value handling to correctly identify which button was clicked based on the `clickedButton()` method.

These changes ensure that the QMessageBox displays the correct button texts and accurately returns the index of the clicked button, resolving compatibility issues between PyQt5 and PySide6.
