### ISSUE TITLE
Failing while importing shapefiles

### ISSUE THREAD

**Issue by r-monti14** [gecos-lab/PZero#95]
In the class_refactoring branch, when importing a shapefile, ‘property’ does not support the direct assignment of elements. The error is related to the ‘feature’ attribute of the shapefile.

 File "D:\REPOS\PZero\pzero\project_window.py", line 2287, in import_SHP
    shp2vtk(self=self, in_file_name=in_file_name, collection=coll)
  File "D:\REPOS\PZero\pzero\imports\shp2vtk.py", line 118, in shp2vtk
    curr_obj_dict["feature"] = i
TypeError: 'property' object does not support item assignment

**Comment by r-monti14** [comment]
Message error after import of dips:

geometry type:  Point
CRS:
 EPSG:2056
Column names of GeoDataframe:  ['dir', 'dip', 'feature', 'geometry']
GeoDataframe:
        dir  dip                       feature                         geometry
0      328   35    Orientierung der Schichten  POINT (2752288.012 1254154.948)
1      334   40    Orientierung der Schichten  POINT (2757214.260 1254209.902)
2      347   55    Orientierung der Schichten  POINT (2757952.139 1254792.165)
3      336   50    Orientierung der Schichten  POINT (2758625.529 1254983.458)
4      352   45    Orientierung der Schichten  POINT (2758518.552 1254731.752)
...    ...  ...                           ...                              ...
28123   16   15  Orientierung der Faltenachse  POINT (2575813.054 1083513.170)
28124  174   15  Orientierung der Faltenachse  POINT (2574028.137 1079750.303)
28125   23   25  Orientierung der Faltenachse  POINT (2575429.181 1082702.374)
28126   62   35  Orientierung der Faltenachse  POINT (2576391.110 1080574.634)
28127  170   45  Orientierung der Faltenachse  POINT (2573735.348 1085142.922)

[28128 rows x 4 columns]
Traceback (most recent call last):
  File "D:\REPOS\PZero\pzero\project_window.py", line 2287, in import_SHP
    shp2vtk(self=self, in_file_name=in_file_name, collection=coll)
  File "D:\REPOS\PZero\pzero\imports\shp2vtk.py", line 118, in shp2vtk
    curr_obj_dict["feature"] = i
TypeError: 'property' object does not support item assignment

**Comment by andrea-bistacchi** [comment]
Ok this is a **bug** because the object being assigned should be a value of a dictionary, identified by its key, not a property.

Could you add a 'print' to show the dictionary and its properties (with 'dir')?

**Comment by r-monti14** [comment]
Here some 'print':
Debug: collection = Geology
Debug: type(collection) = <class 'str'>
Debug: type(GeologicalCollection.entity_dict) = <class 'property'>
Debug: GeologicalCollection.entity_dict = <property object at 0x0000018004C0B630>
Debug: dir(GeologicalCollection.entity_dict) = ['__class__', '__delattr__', '__delete__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass_
_', '__isabstractmethod__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__set__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'deleter', 'fdel', 'fget', 'fset', 'getter', 'setter']

**Comment by andrea-bistacchi** [comment]
OK, it's like I thought. Thanks! I'll try and solve it.

**Comment by waqashussain117** [comment]
**shp2vtk.py**:
- **Resolved 'TypeError: 'property' object does not support item assignment'** by accessing `entity_dict` via instances rather than directly from the class. This ensures that `curr_obj_dict` is a dictionary that can be modified as intended.
- **Fixed 'TypeError: Could not find a suitable VTK type for object'** by:
  - Properly extracting coordinate data from Shapely geometries using `.coords` and converting them into lists before creating NumPy arrays.
  - Specifying `dtype=float` when creating NumPy arrays to ensure they have a numerical data type acceptable to VTK.
  - Ensuring that all `outXYZ` arrays have a consistent numerical data type (`float64`) throughout the code.
- **Updated coordinate extraction and data type handling** for all geometry types (LineString, MultiLineString, Point) to ensure consistency and prevent data type mismatches.
- **Added debug statements** to verify data types and shapes of arrays during processing, aiding in troubleshooting and ensuring data integrity.
- **Improved error handling** by checking for invalid or empty geometries before processing, which prevents unexpected errors during data import.

**legend_manager.py**:
- **Fixed TypeErrors** by casting `numpy.float64` values to `int` before passing them to `QSpinBox.setValue()`. This ensures compatibility with functions expecting integer types and prevents runtime errors when setting spinner values.

I fixed these errors while importing shape files. The main issue was the access to entity dict withing Geological Collection. I have change the code across different files. Similarly, the shape of the files were not properly passed so I added coords to the end of the geometry of the shape file to get the right shape across to the VTK for viewing.
